wordlists:
  short: "/usr/share//dirbuster/short_wordlist.txt"
  medium: "/usr/share/dirbuster/medium_wordlist.txt"
  long: "/usr/share/dirbuster/long_wordlist.txt"
default_scan_options:
  nmap: "-F"
  nikto: "-h"
  sqlmap: "--batch"
