# ------------------------------
# SCRIPT GENERAL SETTINGS
# ------------------------------
general:
  # Define the logging level for the script. Options include: debug, info, warn, error.
  logging_level: "info"
  
  # Specify the directory where the script should save its output or logs.
  output_directory: "/home/user/output"

# ------------------------------
# WORDLIST CONFIGURATIONS
# ------------------------------
wordlists:
  # Define paths for various wordlist sizes.
  short: "/usr/share/dirbuster/short_wordlist.txt"
  medium: "/usr/share/dirbuster/medium_wordlist.txt"
  long: "/usr/share/dirbuster/long_wordlist.txt"
  
  # Default wordlist used by GoBuster in Kali Linux.
  go: "/usr/share/wordlists/dirb/common.txt"

# ------------------------------
# TOOL-SPECIFIC CONFIGURATIONS
# ------------------------------
tools:
  # Nmap scanner settings.
  nmap:
    default_args: "-F"
    path: "/usr/bin/nmap"

  # Nikto scanner settings.
  nikto:
    default_args: "-h"
    path: "/usr/bin/nikto"

  # SQLMap scanner settings.
  sqlmap:
    default_args: "--batch"
    path: "/usr/bin/sqlmap"

  # GoBuster scanner settings.
  gobuster:
    default_args: "--wordlist=/usr/share/wordlists/dirb/common.txt"
    path: "/usr/bin/gobuster"

# ------------------------------
# ADDITIONAL CONFIGURATIONS
# ------------------------------
# Place any other configurations or settings below this section.
